### ISSUE TITLE
Deprecation warning regarding 'include'

### ISSUE THREAD

**Issue by bretrzaun** [iuri-gg/ansible-role-yarn#10]
Using Ansible 2.4 I'm seeing this deprecation warning:
`
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
`

**Comment by ocha** [comment]
yes. I think it is just a simple fix to change `include` with `include_tasks`. I dont have bandwidth right now to fix it. I will try to get to it next week. if you have a fork with fixed code feel free to submit the PR. CI tests will point out if there is any problem

**Comment by iuri-gg** [comment]
v1.2.2 is up. Thanks again @bretrzaun
